name: Merge a branch into another

on:
  workflow_call:
    inputs:
      source-branch:
        required: true
        type: string
      target-branch:
        required: true
        type: string

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge source branch into target branch
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: ${{ inputs.source-branch }}
          target_branch: ${{ inputs.target-branch }}
          message: Github Actions auto-merge
          github_token: ${{ secrets.GITHUB_TOKEN }}
